action 수정 1. 이전 jar 삭제 2. 이전 빌드캐시, 이미지, 컨테이너 완전 정리 추가 3. build, up을 하나로 통합

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,10 +30,19 @@ jobs:
         run: |
             echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > private_key.pem
             chmod 600 private_key.pem
+            # build/libs에서 실행 가능한 하나의 .jar 파일 이름만 찾기
+            # (-plain.jar 같은 파일을 제외합니다)
+            JAR_FILE=$(find $GITHUB_WORKSPACE/build/libs -name "*.jar" ! -name "*-plain.jar" | head -n 1)
+            
+            if [ -z "$JAR_FILE" ]; then
+              echo "ERROR: No executable .jar file found."
+              exit 1
+            fi
+            echo "Found .jar file: $JAR_FILE"
             # 이전 .jar 먼저 삭제
-            ssh -o StrictHostKeyChecking=no -i private_key.pem -p 2222 ubuntukjy@${{ secrets.HOST_IP }} 'rm -f /spring/docker/compose/old_front/jar/*.jar'
+            ssh -o StrictHostKeyChecking=no -i private_key.pem -p 2222 ubuntukjy@${{ secrets.HOST_IP }} 'rm -f /spring/docker/compose/gateway/jar/*.jar'
             # 새로운 .jar 복사
-            scp -o StrictHostKeyChecking=no -i private_key.pem -P 2222 $GITHUB_WORKSPACE/build/libs/*.jar ubuntukjy@${{ secrets.HOST_IP }}:/spring/docker/compose/gateway/jar
+            scp -o StrictHostKeyChecking=no -i private_key.pem -P 2222 $JAR_FILE ubuntukjy@${{ secrets.HOST_IP }}:/spring/docker/compose/gateway/jar
             
       - name: Set SSH ssh-action
         uses: appleboy/ssh-action@master
@@ -46,9 +55,13 @@ jobs:
                   # 이건 ssh연결 된 상태에서 실행되는거라 추후에 dockerfile build나 이런거 할 때 여기에 명령어 작성하면 될듯 아래 명령어들은 다 쓰레기임
                   echo "CD start" 
                   cd /spring/docker/compose
+                  # 빌드캐시, 이미지, 이전 컨테이너 완전 정리
+                  docker builder prune -af || true
+                  docker image prune -af || true
+                  docker container prune -f || true
+
                   docker-compose -f docker-compose-gateway.yaml down -v
                   # 이미지 강제로 전부 삭제, true는 이미지없어서 오류나도 계속 진행하라는 의미
                   docker rmi $(docker-compose -f docker-compose-gateway.yaml images -q) || true
-                  docker-compose -f docker-compose-gateway.yaml build --no-cache
-                  docker-compose -f docker-compose-gateway.yaml up -d --force-recreate
+                  docker-compose -f docker-compose-gateway.yaml up -d --build --force-recreate
                   echo "CD end"
